// redux/constants/channelConstants.js
export const CHANNEL_TYPES = {
    // Carga y listado
    CHANNEL_LOADING: 'CHANNEL_LOADING',
    GET_CHANNEL: 'GET_CHANNEL',
    GET_CHANNELS: 'GET_CHANNELS',
    CLEAR_CHANNEL: 'CLEAR_CHANNEL',
  
    // Seguir / dejar de seguir
    FOLLOW_CHANNEL: 'FOLLOW_CHANNEL',
    UNFOLLOW_CHANNEL: 'UNFOLLOW_CHANNEL',
    GET_USER_CHANNELS: 'GET_USER_CHANNELS',
    // Videos del canal
    GET_CHANNEL_VIDEOS: 'GET_CHANNEL_VIDEOS',
    CHANNEL_FEED_LOADING: 'CHANNEL_FEED_LOADING',
    GET_CHANNEL_FEED_VIDEOS: 'GET_CHANNEL_FEED_VIDEOS',
    CLEAR_CHANNEL_FEED: 'CLEAR_CHANNEL_FEED',
    // Estadísticas y vistas
    CHANNEL_STATS: 'CHANNEL_STATS',
    REGISTER_CHANNEL_VIEW: 'REGISTER_CHANNEL_VIEW',
  
    // Seguidores / seguidos
    GET_CHANNEL_FOLLOWERS: 'GET_CHANNEL_FOLLOWERS',
    GET_USER_FOLLOWING_CHANNELS: 'GET_USER_FOLLOWING_CHANNELS',
  
    // Actualizar canal
    UPDATE_CHANNEL: 'UPDATE_CHANNEL',
    UPDATE_CHANNEL_SETTINGS: 'UPDATE_CHANNEL_SETTINGS',
  };